core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('food/<int:pk>/', views.detail_view.as_view(), name='detail'),
    path('additem/', views.CreateItem.as_view(), name='create_item'),
    path('updateitem/<int:id>/', views.update_item, name='update_item'),
    path('deleteitem/<int:id>/', views.delete_item, name='delete_item')
]

foodapp/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('profile/',user_views.profilepage, name = 'profilepage')
]




urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.



class Item(models.Model):
    
    def __str__(self):
        return f'{self.item_name} {self.item_price} '
    
    user_name = models.ForeignKey(User,on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length = 200)
    item_desc = models.CharField(max_length = 200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=1000, default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    def get_absolute_url(self):
        return reverse("core:detail",kwargs={"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to= 'profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

core/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

core/views.py
from django.shortcuts import render, HttpResponse,redirect
from .models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# Create your views here.

# def index(request):
#     item_list = Item.objects.all()
#     context = {
#         'item_list': item_list,
#     }
#     # template = loader.get_template('core/index.html')
#     # return HttpResponse(template.render(context, request))
#     return render(request, 'core/index.html', context)

class IndexView(ListView):
    model = Item
    template_name = 'core/index.html'
    context_object_name = 'item_list'

class detail_view(DetailView):
    model = Item
    template_name = 'core/detail.html'

# def detail(request, item_id):
#     item = Item.objects.get(pk = item_id)
#     context = {
#         'item':item,
#     }
#     return render(request,'core/detail.html', context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('core:index')
    
    return render(request,'core/item-form.html',{'form':form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'core/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request,id):
    item = Item.objects.get(id = id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('core:index')
    
    return render(request, 'core/item-form.html', {'form':form, 'item':item})


def delete_item(request, id):
    item = Item.objects.get(id = id)

    if request.method == 'POST':
        item.delete()
        return redirect('core:index')

    return render(request, 'core/item-delete.html',{'item': item})



   

users/views.py
from django.shortcuts import render, redirect

from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def register(request):

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f"Welcome {username}! Your account has been succesfully created")
            return redirect('login')
    else:
        form = RegisterForm()

    return render(request, 'users/register.html', {'form': form})


@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{%static 'core/style.css'%}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
</head>
<body>


    <nav class = "navbar navbar-dark bg-dark">
        <a href="#" class = "navbar-brand">Food App</a>
        <div class = "navbar">
            <a href="{% url 'core:create_item' %}" class = "nav-item">Add Item</a>
            <a href="#" class = "nav-item" >Delete Item</a>
            <a href="#" class = "nav-item">View Item</a>
            {% if user.is_authenticated %}
            <form action = "{% url 'logout' %}" method = "post">
                {% csrf_token %}
            <button type = "submit">Logout</button>
            <a href = "{% url 'profilepage' %}">Profile</a>
            </form>
            {% else %}
            <a href = "{% url 'login' %}">Login</a>
          
            {% endif %}
        </div>

    </nav>
    {% if messages%}
    {% for message in messages %}
        <div class = "alert alert--{{message.tags}}">{{message}}</div> 
    {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

core/templates/core/detail.html
{% extends 'core/base.html' %}



{% block body %}
<div class="container">
    <div class = "row">
    <div class = "col-md-6">
      <img src="{{item.item_image}}" class = "card" width="400px">
    </div>
    <div class = "col-md-6">
        <h1>{{object.item_name}}</h1>
        <h2>{{object.item_desc}}</h2>
        <h3>{{object.item_price}}</h3>
        <a href="{% url 'core:delete_item' item.id %}">Delete Item</a>
    </div>
</div>
</div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     
</head>
<body>


   {% block body %}
   
   {% for item in item_list %}
   <div class = "row">
    <div class = "col-md-2 offset-md-2">
      <img src="{{item.item_image}}" class = "card" height="150px" width="150px">

    </div>
    <div class = "col-md-4">
        
        <h3>{{item.item_name}}</h3>
        <h5>{{item.item_desc}}</h5>
        <h6>{{item.item_price}}</h6>
        <h4>{{item.user_name}}</h4>
    </div>
    <div class = "col-md-2">
        <a href="{% url 'core:detail' item.id %}" class = "btn btn-success">Detail</a>
     
    </div>

   </div>
   {% endfor %}
   {% endblock %}

    
</body>
</html>

core/templates/core/item-delete.html
<form method = "POST">
    {% csrf_token %}
<h3>Are you sure you want to delete the item {{item.item_name}}?</h3>
<button type = "submit">Confirm</button>
</form>

core/templates/core/item-form.html
 {% extends "core/base.html" %}

 {% block body %}


<form method = "POST">
{% csrf_token %}

{{form}}


<button type = "submit" >Submit</button>

</form>
{% endblock %}

users/templates/users/login.html
<form method = "POST">
{% csrf_token %}
{{form}}
<button type= "submit">Login</button>
</form>

users/templates/users/logout.html
<h2>You have been successfully logged out!</h2>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src = "{{ user.profile.image.url }}">

users/templates/users/register.html
<form method = "POST">
    {% csrf_token %}

    {{form}}
    <button type = "submit" >Sumbit</button>
</form>